directory "classes"
task :default => "classes" do
  ENV["CLASSPATH"] = RUBY_PLATFORM.index("darwin") ? "/Users/moumar/Applications/Processing.app/Contents/Resources/Java/core.jar" : "~/src/processing/lib/core.jar"
  sh "cd classes; javac -source 1.5 -target 1.5 -d . -Xlint:unchecked ../net/moumar/*.java"
  sh "cd classes; jar -cf ../../library/valuerecorder.jar ."
end
